### ISSUE TITLE
Un bootloop after install on LG G8 820n Arrow12

### ISSUE THREAD

**Issue by Canajuana** [KamioRinn/LGE_G820_Kernel_Wish#7]
I tried to flash 1.2 Dragon Fly over clocking but got un bootloop on LG g820n with Arrow12 OS. How can i update this kernel via magisk for my phone. please?

**Comment by RainyWhite** [comment]
Hello Canawan, as you can see, our kernel is no longer maintained. I recommend you to use Dragonfly because there is no other choice. About bootloopp, our Kernel are built for official firmware. And u know that Arrow12 is not a GSI, so the kernel of them two have some differences. Maybe will leads to bootloop :(

**Comment by Canajuana** [comment]
Oke, I see that, now my phone get back to stock firmware  and i will try gain. Tks for this kernel!!!
